### ISSUE TITLE
Permissions of /home/aiida folder wrong?

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-docker-stack#34]
I'm trying to run this container, and it seems the owner of (parts of) the ``/home/aiida`` folder is ``root``, which causes issues when trying to log in as ``aiida`` user. Since I'm not very well-versed (a.k.a a complete newbie) at using Docker, it might just be that I'm doing something wrong.

What I'm doing is the following (in the root directory of this repo):

```
docker build .
docker run -it <identifier> /bin/bash
su aiida
```

This gives the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiida/manage/configuration/settings.py", line 63, in create_directory
    os.makedirs(path)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/aiida/.aiida/daemon'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/verdi", line 5, in <module>
    from aiida.cmdline.commands.cmd_verdi import verdi
  File "/usr/local/lib/python3.6/dist-packages/aiida/__init__.py", line 30, in <module>
    from aiida.common.log import configure_logging
  File "/usr/local/lib/python3.6/dist-packages/aiida/common/__init__.py", line 25, in <module>
    from .log import *
  File "/usr/local/lib/python3.6/dist-packages/aiida/common/log.py", line 26, in <module>
    from aiida.manage.configuration import get_config_option  # pylint: disable=wrong-import-position
  File "/usr/local/lib/python3.6/dist-packages/aiida/manage/configuration/__init__.py", line 16, in <module>
    from .config import *
  File "/usr/local/lib/python3.6/dist-packages/aiida/manage/configuration/config.py", line 23, in <module>
    from .profile import Profile
  File "/usr/local/lib/python3.6/dist-packages/aiida/manage/configuration/profile.py", line 23, in <module>
    from .settings import DAEMON_DIR, DAEMON_LOG_DIR  # pylint: disable=wrong-import-position
  File "/usr/local/lib/python3.6/dist-packages/aiida/manage/configuration/settings.py", line 116, in <module>
    set_configuration_directory()
  File "/usr/local/lib/python3.6/dist-packages/aiida/manage/configuration/settings.py", line 112, in set_configuration_directory
    create_instance_directories()
  File "/usr/local/lib/python3.6/dist-packages/aiida/manage/configuration/settings.py", line 49, in create_instance_directories
    create_directory(directory_daemon)
  File "/usr/local/lib/python3.6/dist-packages/aiida/manage/configuration/settings.py", line 66, in create_directory
    raise ConfigurationError("could not create the '{}' configuration directory".format(path))
aiida.common.exceptions.ConfigurationError: could not create the '/home/aiida/.aiida/daemon' configuration directory
```

In the home directory:
```
aiida@74772a960df7:~$ ll
total 36
drwxr-xr-x 1 aiida aiida 4096 Nov 19 16:46 ./
drwxr-xr-x 1 root  root  4096 Nov  1 08:52 ../
drwx------ 3 root  root  4096 Nov 19 16:46 .aiida/
-rw-r--r-- 1 root  root   220 Nov  1 08:52 .bash_logout
-rw-r--r-- 1 root  root  3880 Nov  1 08:52 .bashrc
drwxr-xr-x 3 aiida aiida 4096 Nov  1 08:52 .config/
-rw-r--r-- 1 root  root   807 Nov  1 08:52 .profile
drwx------ 2 aiida aiida 4096 Nov  1 08:52 .ssh/
```

Am I doing something wrong, or is there an issue in how the container is set up? The same happens if I try to use the pre-built version from Dockerhub.

**Comment by greschd** [comment]
To answer my own question here: I think I was supposed to just start the container with ```docker run <identifier>```, and then attach to it with ```docker exec -it <container_name> bash```.

When running it with an explicit command, the ```CMD ["/sbin/my_init"]``` has no effect, which is actually what sets up the aiida profile (as root).
